import React from 'react';
import { Icons } from './ui/icons';

interface DocumentPreviewProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  content: string;
  onDownload?: () => void;
  onPrint?: () => void;
}

const DocumentPreview: React.FC<DocumentPreviewProps> = ({ isOpen, onClose, title, content, onDownload, onPrint }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-4xl h-[85vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-white z-10">
          <div className="flex items-center gap-3">
            <div className="bg-emerald-100 text-emerald-600 p-2 rounded-lg">
              <Icons.Actions.FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-800">{title}</h3>
              <p className="text-xs text-slate-500">Generated by JobOpti AI</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onPrint}
              className="p-2 text-slate-500 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors"
              title="Print"
            >
              <Printer className="w-5 h-5" />
            </button>
            <button
              onClick={onDownload}
              className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
            >
              <Download className="w-4 h-4" /> Download PDF
            </button>
            <button
              onClick={onClose}
              className="ml-2 p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
            >
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto bg-slate-100 p-8">
          <div className="bg-white shadow-sm border border-slate-200 min-h-full mx-auto max-w-[21cm] p-[2.5cm] text-slate-800 text-sm leading-relaxed whitespace-pre-wrap font-serif">
            {content}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentPreview;
